number:
# dispaly setting 
# time for return to weather card
  - platform: lvgl
    widget: return_spin
    name: "Screen Return Time"    
    id: return_timeout
    unit_of_measurement: "s"
    restore_value: false
    mode: box
    entity_category: config
    
# time for turn off the lcd 
  - platform: lvgl
    widget: idle_spin
    name: "LCD Screen Timeout"    
    id: screen_timeout
    unit_of_measurement: "s" 
    restore_value: false
    mode: box
    entity_category: config

  - platform: lvgl
    widget: slide_brightness
    id: backlight_brightness
    unit_of_measurement: "%"
    #initial_value: 50
    restore_value: true
    mode: box
    entity_category: config
          
# Presece for turn on/off the display
binary_sensor:
  - platform: homeassistant
    entity_id: $presence
    id: presence_sensor    
    on_press:
      - light.turn_on: backlight
    on_release: 
      - light.turn_off: backlight
# lux sensor for auto brightness
sensor:
  - platform: homeassistant
    entity_id: $illuminance
    id: lux_sensor  
